HairSalon/Models/Clients.cs
using MySqlConnector;


namespace HairSalon.Models


{
  public class Client
  {
    public int ClientId { get; set;}
    public string  Name { get; set; }
    public string Regular {get; set; }
    public string Last { get; set; }
    public int Total { get; set; }
    public int StylistId { get; set; }
    public Stylist Stylist { get; set; }
  }
}

HairSalon/Models/HairSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
  public class HairSalonContext : DbContext
  {
    public DbSet<Stylist> Stylists { get; set; }
    public DbSet<Client> Clients { get; set; }

    public HairSalonContext(DbContextOptions options) : base(options) { }
  }

}

HairSalon/Models/Stylist.cs
using System.Collections.Generic;




namespace HairSalon.Models
{

  public class Stylist
  {
  
    public int StylistId { get; set;}
    public string Name { get; set; }
    public string Hired { get; set; }
    public List<Client> Clients { get; set; }

  }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;

namespace HairSalon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly HairSalonContext _db;

    public ClientsController(HairSalonContext db)
    {
      _db = db;
    }

      public ActionResult Index()
    {
      List<Client> model = _db.Clients
                                .Include(client => client.Stylist)
                                .ToList();
      return View(model);
    }

    public ActionResult Create()  //?
    {
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View();
    }

      [HttpPost]
      public ActionResult Create(Client client)
    {
      if (client.StylistId == 0) //checks if StylistId for the clients element is 0
      {
        return RedirectToAction("Create");  //Redirects to Create View if the StylistId is 0
      }
      _db.Clients.Add(client);   //Adds Stylist to client table within _db 
      _db.SaveChanges();  //saves changes to database
      return RedirectToAction("Index"); //redirects to Index
    }

    public ActionResult Details(int id)
    {
      Client thisClient = _db.Clients
                          .Include(client => client.Stylist)
                          .FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }

    public ActionResult Edit(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View(thisClient);
    }

    [HttpPost]  //posting our client edit the database
    public ActionResult Edit(Client client) //takes in client object
    {
      _db.Clients.Update(client); //calles Clients table to Update the Client instance
      _db.SaveChanges();  //saves changes of the updated client instance above
      return RedirectToAction("Index"); //redirects to Index of Client View
    }

    public ActionResult Delete(int id)
    {
      Client deleteClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      return View(deleteClient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Client deleteClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      _db.Clients.Remove(deleteClient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

//askdlasldlaskdlkasldka
  }
}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HairSalon.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }
    }
}

HairSalon/Controllers/StylistController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;

namespace HairSalon.Controllers
{
  public class StylistController : Controller
  {
    private readonly HairSalonContext _db;

    public StylistController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylist.ToList();
      return View (model);
    }

    public ActionResult Create()
    {
      return View();
    }

      [HttpPost]

      public ActionResult Create(Stylist stylist)
      {
        _db.Stylist.Add(stylist);
        _db.SaveChanges();
        return RedirectToAction("Idex");
      }

      public ActionResult Details(int id)  // ?
    {
      Stylist thisStylist = _db.Stylist
                                        .Include(stylist => stylist.Clients)
                                        .FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    public ActionResult Edit( int id)
    {
      Stylist thisStylist = _db.Stylist.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost]
    public ActionResult Edit(Stylist stylist)
    {
      _db.Stylist.Update(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

      public ActionResult Delete(int id)
      {
        Stylist thisStylist = _db.Stylist.FirstOrDefault(stylist => stylist.StylistId == id);
        return View(thisStylist);
      }

      [HttpPost, ActionName("Delete")]
      public ActionResult DeleteConfirmed(int id)
      {
        Stylist thisStylist = _db.Stylist.FirstOrDefault(stylist => stylist.StylistId == id);
        _db.Stylist.Remove(thisStylist);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }


  }
}

HairSalon/Controllers/StylistsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;

namespace HairSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly HairSalonContext _db;

    public StylistsController(HairSalonContext db)
    {
      _db = db;
    }


    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.ToList();
      return View(model);
    }


    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
      _db.Stylists.Add(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Stylist stylistDetails = _db.Stylists
                                    .Include(stylist => stylist.Clients)
                                    .FirstOrDefault(stylist => stylist.StylistId == id);
      return View(stylistDetails);
    }

    public ActionResult Edit( int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost]
    public ActionResult Edit(Stylist stylist)
    {
      _db.Stylists.Update(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

      public ActionResult Delete(int id)
      {
        Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
        return View(thisStylist);
      }

      [HttpPost, ActionName("Delete")]
      public ActionResult DeleteConfirmed(int id)
      {
        Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
        _db.Stylists.Remove(thisStylist);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }


  }
}

HairSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h1><u>Add New Client</u></h1>

@using (Html.BeginForm())
{
 @Html.TextBoxFor(model => model.Name, new { placeholder = "First Name:"})<br><br>

 @Html.TextBoxFor(model => model.Regular, new { placeholder = "Last Name:"})<br><br>

 @Html.TextBoxFor(model => model.Last, new { placeholder = "Regular:"})<br><br>

@Html.TextBoxFor(model => model.Total, new { placeholder = "Total Price:"})<br><br>

<br>
@Html.DropDownList("StylistId")
<br><br>
<button class="btn btn-danger btn-lg" type="submit">Add Clients</button>
<br><br>
}

HairSalon/Views/Clients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client


<h2><u>Are you sure you want to delete this?</u></h2>


@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

@Html.ActionLink("Back To List", "Idex")

HairSalon/Views/Clients/Details.cshtml
@{
Layout = "_Layout";
}

@model HairSalon.Models.Client


<h1><u>Client Detail:</u></h1>

  <p>@Html.DisplayFor(model => model.Name)</p>
  <p>@Html.DisplayNameFor(model => model.Regular) Cut: @Html.DisplayFor(model => model.Regular)</p>

  <p>@Html.DisplayNameFor(model => model.Last) Visit: @Html.DisplayFor(model => model.Last)</p>
  <p>@Html.DisplayNameFor(model => model.Total) Total: @Html.DisplayFor(model => model.Total)</p>

  <p>Stylist: @Html.DisplayFor(model => model.Stylist.Name)</p>

  <button>@Html.ActionLink("Edit Client", "Edit", new { id = Model.ClientId})</button>
  <button>@Html.ActionLink("Delete Client", "Delete", new { id = Model.ClientId })</button>
  <button>@Html.ActionLink("Back To Clients", "Index")</button>

HairSalon/Views/Clients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2><u>Edit Clients</u></h2>


<h4>Edit This Client: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{

@Html.HiddenFor(model => model.ClientId)
@Html.EditorFor(model => model.Name)
@Html.DropDownList("StylistId")


  <button type="submit">Save Client</button>
}
<br>
<button>@Html.ActionLink("Back to Clients", "Index")</button>  

HairSalon/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Client>;

  <h2><u>Clients List</u></h2>

  <div>
    @if (@Model.Count == 0)
    {
      <h3><u>No Clients Added Yet!</u></h3>
    }

  @foreach (Client client in Model)
  {
    <p>@Html.ActionLink($"{client.Name}", "Details", new { id = client.ClientId }) | @client.Stylist.Name</p>
  }
  </div>

  <p>@Html.ActionLink("Add New Client", "Create")</p>
  <p>@Html.ActionLink("Back To Home", "Index")</p>

HairSalon/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}
<body>
<h1><u>Welcomed To Eau Claire's Salon</u></h1>

<div class="row">
<div class="col">
<button type="button" class="btn btn-danger btn-lg">@Html.ActionLink("Clients", "Index", "Clients")</button> 
</div>
<div class="col">
<button  type="button" class="btn btn-danger btn-lg">@Html.ActionLink("Stylist", "Index", "Stylists")</button>
</div>
</div>
</body>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hair Salon</title>
    <link 
      rel="stylesheet" 
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" 
      crossorigin="anonymous">
       <link href="https://fonts.googleapis.com/css2?family=Merriweather&family=Montserrat&family=Sacramento&display=swap"
    rel="stylesheet">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="navbar">
  <a class="navbar-brand" href="#"><u>Eau Claire's Salon</u></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href='/'>Home <span class="sr-only">(current)</span></a>  <!--Home Page-->
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a> <!-- currently empty -->
      </li>
      <li class="nav-item">
        <a class="nav-link" href='/Clients'>Clients</a> <!--Clients Page-->
      </li>
      <li class="nav-item">
        <a class="nav-link" href='/Stylists'>Stylists</a>  <!--Stylist Page-->
      </li>
    </ul>
  </div>
</nav>
<div class="container">
@RenderBody()
</div>
  </body>
</html>

HairSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}
@model HairSalon.Models.Stylist

<h2><u>Add New Stylist</u></h2>

@using (Html.BeginForm())
{
  @Html.TextBoxFor(model => model.Name, new { placeholder = "First Name:"})
  <br><br>
  @Html.TextBoxFor(model => model.Hired, new { placeholder = "Hired:"})
  <br><br>
  <button class="btn btn-danger btn-lg" type="submit"> Add</button>
}

HairSalon/Views/Stylists/Delete.cshtml
@{
  Layout = "_Layout";
}


@model HairSalon.Models.Stylist


<p>Deleting @Model.Name</p>

<p>Are you are you want to delete this?</p>

@using (Html.BeginForm())
{
  <button type="submit">Delete</button>
}

<button>@Html.ActionLink("Back to List", "Index")</button>

HairSalon/Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist
@using HairSalon.Models

<h2><u>Information</u></h2>

<p>@Html.DisplayFor(model => model.Name)</p>
<p>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</p>
<p>@Html.DisplayNameFor(model => model.Hired): @Html.DisplayFor(model => model.Hired)</p>

<button>@Html.ActionLink("Edit Stylist", "Edit", new { id = Model.StylistId})</button>
<button>@Html.ActionLink("Delete Stylist", "Edit", new { id = Model.StylistId})</button>
<button>@Html.ActionLink("Back To Stylist", "Index")</button>

<h4>Clients</h4>
@foreach(Client client in Model.Clients)
{
  <li>@Html.ActionLink($"{client.Name}", "Details", "Clients", new {id = client.ClientId})</li>
}

HairSalon/Views/Stylists/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h2>Edit</h2>

<h4> Edit this Stylist: @Html.DisplayFor(model => model.Name)</h4>


@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StylistId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  @Html.LabelFor(model => model.Hired)
  @Html.EditorFor(model => model.Hired)

  <input type="submit" value="save" />
}
<p>@Html.ActionLink("Back To list", "Index")</p>

HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;

<h1>Stylists</h1>

@if (@Model.Count == 0)
{
  <h3>No Stylist has been added yet!</h3>
}

<ul>
  @foreach (Stylist stylist in Model)
  {
    <li>@Html.ActionLink($"{stylist.Name}", "Details", new { id = stylist.StylistId})</li>
  }
</ul>

<p>@Html.ActionLink("Add new Stylist", "Create")</p>
<p>@Html.ActionLink("Add new Client", "Create", "Clients")</p>
<p>@Html.ActionLink("Back to home", "Index", "Home")</p>